### ISSUE TITLE
On command execution failure in a saga, take the failure events and pass them back to the saga

### ISSUE THREAD

**Issue by daviddawson** [muoncore/newton#49]
When a command fails (an uncontrolled exception), if the saga has an @EventHandler for the new CommandFailedEvent, construct that event and re-invoke the saga with it.

That event should contain sufficient information to handle the command failure and take the appropriate action.

**Comment by bobjana** [comment]
The above proposed solution will work well for deciding how to handle a failure within a Saga. Perhaps as another feature, the actual saga's status could be updated for reporting purposes
